### ISSUE TITLE
up/down could be run in transaction to support multiple statements correctly

### ISSUE THREAD

**Issue by wkhere** [go-pg/migrations#10]
Hi!

If I have multiple `db.Exec`s in a migration, there's a bug: if a second `Exec` fails the changes from the first are already committed. It makes the migration not revertible.

The proper solution would be to execute both up & down in a transaction. Can this be done a default?

**Comment by herenowcoder** [comment]
Actually, it's not only about making it default, it's about having a valid bevahiour at all.

I was thinking I can have a workaround by running `db.RunInTransaction()` explicitly in my up/down, but `migrations.DB` is not the same as `pg.DB`. So please make the transactions default or expose `RunInTransaction()` in `migrations.DB` ..

**Comment by vmihailenco** [comment]
On of the reasons I wrote this lib is that I don't want transactions by default. See https://bitbucket.org/liamstask/goose/issues/15/ability-to-run-migrations-without-the .

I think they way forward is to change your https://github.com/go-pg/migrations/blob/v4/example/main.go#L18-L26 to open transaction:

```
	db := pg.Connect(&pg.Options{
		User:     "postgres",
		Database: "pg_migrations_example",
	})

        err := db.RunInTransaction(db, func(tx *pg.Tx) error {
            _, _, err := migrations.Run(tx, flag.Args()...)
            return err
        })
	if err != nil {
		exitf(err.Error())
        }
```

That will run all migrations in one big transaction though. As a workaround we can add `go run *.go up_one` that will apply only 1 migration at a time.

I will also expose `RunInTransaction` in migrations.DB, but you can already use it via `db.(*pg.DB).RunInTransaction`.

**Comment by herenowcoder** [comment]
Thanks for a quick reply!

2cents, IMO throwing out the transactions (and a predictable behavior they give) just because of one rarely used Pg feature which doesn't work with them is, well, I wouldn't do that ;).

Having said that, looks like you gave a solution, which is nice :]

Let me summarize a different aspects here:

1. Wrapping the whole run in a transaction from `main()` as you wrote - this may be even desired behaviour (if the migrations are dependent on each other for example). I think I can adapt this.

2. Running each migration in a transaction - note that transaction should wrap Up/Down together with updating version. You don't want to introduce this change in the code. Can be emulated by `up_one`.

3. Adding `RunInTransaction` to `migrations.DB` (thanks for the obvious tip with casting!):  after a thought I realized it will not solve my initial issue, because it will be isolated from updating the version - see (2). So it's only helpful if somebody would want to run *subtransactions* in his migration. Which is a rare case I suppose.

**Comment by herenowcoder** [comment]
To sum up:

* Adding `RunInTransaction` to `migrations.DB` seems like a rare case
* `up_one` would be a nice addition.

**Comment by herenowcoder** [comment]
Btw, (3) makes even less sense because `pg.v4` right now doesn't support nested transactions.

And yes, a valid case for it is to mix DDL & DML in a migration. I just have a valid case when there's a need to fix some data before altering the schema.

**Comment by owais** [comment]
I think running every migration inside it's own transaction should be the default. Most migrations might have more than one operations and it wouldn't make sense to let one some operations finish and let others fail. That would leave the schema in a broken state. I think it's an important enough to consider reversing how transactions in migrations are handled right now i.e, run every migration in one transaction by default but let the migration specify if it doesn't want that. 

`migrations.Register()` would by default register a migration and run it in a transaction while as `migrations.RegisterUnsafe()` would register but run the migration outside a transaction. This would be a simple enough change to support both use cases while still defaulting on the most safe and practical solution for 99% of migration.

Solutions proposed above fall short IMO.

* Single transaction for all migrations
What is proposed in the read me runs all migrations in a single transaction. That is not really desired as a migration usually represents a single logical operation. For example, `0003_add_table` could add new tables to a DB while `0004_initiate_table` could migrate some data to it from some other source (like a data migration in django for example). If we used a single transaction, 0004 wouldn't be able to operate on the table as the table wouldn't exist.


* Up/down to specific migration
One could migrate 0003 first explicitly and then run migrate again to run 0004 but this is only useful during development. One the code is shipped to production, we would usually want the CI/CD pipeline to run the migrations. Adding this knowledge about migrations to a CI/CD tool is too impractical IMO. 

* Explicitly transaction in migration code
This is good and would accomplish what I'd like to have but we would still have what is in my opinion an unsafe default of running transactions outside migrations. I don't think we should rely on people figuring out that their migrations don't run in transactions by corrupting their production databases. A good default is crucial IMO to mitigate possible data-loss risks. 


I can send work on a PR if you agree with the proposal @vmihailenco

**Comment by vmihailenco** [comment]
This library was created specifically because migrations on big databases can't be run in transaction. See [this](https://www.fin.com/post/2018/1/migrations-and-long-transactions) for example. It is also the current default and I don't want to break backwards compatibility for this feature.
