### ISSUE TITLE
error when trying to get or use

### ISSUE THREAD

**Issue by rcmonitor** [go-pg/migrations#14]
go get returns error, while still downloading package:
`>go get github.com/go-pg/migrations
 github.com/go-pg/migrations
..\github.com\go-pg\migrations\db.go:27: cannot use pg.Q(tableName) (type orm.FormatAppender) as type types.ValueAppender in
return argument:
        orm.FormatAppender does not implement types.ValueAppender (missing AppendValue method)
`
when I'm trying to run examples, it gives the same error:
`>go run main.go init
 github.com/go-pg/migrations
..\..\..\github.com\go-pg\migrations\db.go:27: cannot use pg.Q(tableName) (type orm.FormatAppender) as type types.ValueAppender in return argument:
        orm.FormatAppender does not implement types.ValueAppender (missing AppendValue method)
`

**Comment by vmihailenco** [comment]
Can you try to upgrade? I think it was broken for like 15 minutes yesterday.

**Comment by vmihailenco** [comment]
```
go get -u github.com/go-pg/migrations
```

works for me

**Comment by rcmonitor** [comment]
Yeah, it is fine now. Thx.
