### ISSUE TITLE
Error when trying to execute all migrations at once

### ISSUE THREAD

**Issue by rcmonitor** [go-pg/migrations#15]
I'm using directory structure equivalent to one given in example.
`1_initial.go
2_dictionary_seed.go
...
main.go`

If I'm running one migration at a time, like 
`go run main.go 1_initial.go up`
or 
`go run main.go 1_initial.go down`
It works fine.
But when I'm trying to run all at once, like
`go run *.go up` 
or
`go run *.go down`
It fails with an error:

> GetFileAttributesEx *.go: The filename, directory name, or volume label syntax is incorrect.

**Comment by vmihailenco** [comment]
There is no function with `GetFileAttributesEx` name in this lib. But indeed you should use `go run *.go up`.

**Comment by rcmonitor** [comment]
Does it somehow contradicts my description of an issue?

**Comment by vmihailenco** [comment]
Nope, but you should trace where `GetFileAttributesEx` function comes from

**Comment by rcmonitor** [comment]
Well, unfortunately, there is all the message I've got:
`\migration>go run *.go up


GetFileAttributesEx *.go: The filename, directory name, or volume label syntax is incorrect.`

So, as you can see, there is not much to debug(

**Comment by vmihailenco** [comment]
Well, I guess you are using Windows... I don't have any experience with Go and Windows, but most likely `*.go` syntax is not supported in your Windows shell. In Linux `*.go` is expanded to `1_initial.go 2_dictionary_seed.go main.go` by shell so you need something similar on Windows.

**Comment by vmihailenco** [comment]
See https://github.com/golang/go/issues/3415

**Comment by rcmonitor** [comment]
Ok, thx for investigation.
