### ISSUE TITLE
run migration files from any folder

### ISSUE THREAD

**Issue by SavostinVladimir** [go-pg/migrations#21]
Hi! I try to run your migration example, but I need to store all versions in separate folder.
like this:
![migr](https://user-images.githubusercontent.com/27097483/35319234-1dd3b510-0109-11e8-92bf-a77fc992bf92.PNG)
when I am trying to: "go run migrate.go" , the program could not find the version 1_initMdmDb.go.. How can I define the path to it

**Comment by vmihailenco** [comment]
Probably `go run migrate.go migrate/*.go`, but I did not try.
