### ISSUE TITLE
Allow for easier embedding into a project

### ISSUE THREAD

**Issue by jonaswouters** [go-pg/migrations#3]
Hey,

It is currently difficult to use this package embedded into an existing project.
It would be nice if the "migration" variable would be public, that way we can write an alternative register method that appends Migration structs to this array variable. 

Something like

```
var (
	Migrations []Migration
	sortMu     sync.Mutex
)

func Register(migration Migration) {

	Migrations = append(migrations, migration)
}
```

Perhaps make an alternative method to register migrations by file?

**Comment by vmihailenco** [comment]
Hi,

What do you think about https://github.com/go-pg/migrations/pull/5:

```
migrations.RunMigrations(db, migrations, "up")
```

?

**Comment by jonaswouters** [comment]
Yeah that would work
