### ISSUE TITLE
RunMigrations does not use table specified by SetTableName

### ISSUE THREAD

**Issue by betrok** [go-pg/migrations#40]
RunMigrations creates NewCollection => ignores global SetTableName, which updates DefaultCollection.
It breaks backward compatibility.

**Comment by derlaft** [comment]
https://github.com/go-pg/migrations/pull/38 seems to be related

**Comment by betrok** [comment]
Rather unexpected solution, but at least nobody will accidentally mess their migrations. Ok.

**Comment by Derlafff** [comment]
*nobody else :)
