### ISSUE TITLE
should not lock gopg_migrations table if table does not exist

### ISSUE THREAD

**Issue by diegomanjarres** [go-pg/migrations#44]
error ERROR #42P01 relation \"gopg_migrations\" does not exist. when running migrations for the first time.
It should be check that the table exists before locking

**Comment by vmihailenco** [comment]
Why? What does it fix?

**Comment by Terminator637** [comment]
Is this a bug? I got the same issue.

**Comment by vmihailenco** [comment]
You need to initialize the tool via `go run *.go init`
