### ISSUE TITLE
Create gopg_migrations table when it does not exist with "up" cmd

### ISSUE THREAD

**Issue by mfinley3** [go-pg/migrations#48]
Back around version 6.3.0 the `gopg_migrations` table would be created if it did not exist with the "up" cmd. 

The latest versions (6.5.2 onward) all seem to require that `init` be run separately now. If I'm starting up off of a clean database, I'd like my app to create the`gopg_migrations` table if it does not exist and then run my migrations without running `init` separately.

If I missed how this can easily be done in the latest version, please let me know.

**Comment by vmihailenco** [comment]
Current behavior is less convenient but simplifies the code and makes bugs regarding db/schema/table names more obvious.
