### ISSUE TITLE
Advice for running migrations in a Docker container?

### ISSUE THREAD

**Issue by ernsheong** [go-pg/migrations#49]
I want migrations to run automatically when the application starts in production/staging. Any pointers on how this can be achieved?

Perhaps I need to compile the migration main package into a binary, but how to deal with mixture of .go and .sql files?

**Comment by vmihailenco** [comment]
Can't you run `go run *.go` in a container?

**Comment by ernsheong** [comment]
Go code is compiled to a binary, and go itself is left out of the container. 

Of course there is the option to just include go, but the lightweight preference is binary-only.

**Comment by ernsheong** [comment]
Dockerfile (`main` and `migrate` are built outside of Dockerfile):
```
FROM busybox

COPY cacerts.pem /etc/ssl/certs/
ADD main /

# Add migrate SQL files
ADD migrate/*.sql /
# Add migrate binary
ADD migrate/migrate /
# Add migrate.sh wrapper script
ADD migrate.sh /

EXPOSE 8080

CMD ["/main"]
```

migrate.sh:
```
#!/bin/sh

set -e

/migrate init || true
exec /migrate

```

**Comment by RC1140** [comment]
There is an issue with the way the sql files are found , i made a simple release to force the location to root so that I could build my docker images.

Will try and make this more configurable at a later stage.

https://github.com/RC1140/migrations/releases/tag/v6.6.8

**Comment by ernsheong** [comment]
@RC1140 a PR would be great!! 🙏

**Comment by RC1140** [comment]
Will do , just need to figure out a more viable solution :)

**Comment by RC1140** [comment]
Added pull request , https://github.com/go-pg/migrations/pull/50

**Comment by vmihailenco** [comment]
There is new API `DiscoverSQLMigrations` which allows adding SQL migrations from arbitrary dirs.

**Comment by tpoxa** [comment]
As quick workaround I do next:
```go
...
migrate.InitSafe()
if reset {
  migrate.Reset()
}
migrate.Migrate(argsMig)
...
```

```go
func InitSafe() {
	db, err := db.Connect()
	if err != nil {
		log.Fatal(err)
	}
	_, err = migrations.Version(db)
	if err != nil  {
	    migrations.Run(db, "init")
	}
}
```
But would be better to differ type of error...
