### ISSUE TITLE
The "multiple migrations with version" error occurs when go migration follows sql one

### ISSUE THREAD

**Issue by foxen** [go-pg/migrations#52]
This error rising if I try to add a `.go` migration file in directory where already are `.sql` files.
Seems like a call of `func (c *Collection) discoverSQLMigrations(file string) error`
 in `func (c *Collection) register(tx bool, fns ...func(DB) error) error` cause such behaviour. Is there any reason for the call?

**Comment by vmihailenco** [comment]
If there are multiple migrations with same version such as `1_some.go` and `1_some.up.sql` the lib returns an error. The fix is to rename the file.

**Comment by foxen** [comment]
@vmihailenco Ok, I see it. I figured out what happened in my case. I had separate code from migration file `main.go` in a function which src is located up in a directory tree. So firstly, the `discoverSQLMigrations` scan recursively from a function file dir and add this dir to the `Collection.visitedDirs` map. Then a `.go` migration starts `discoverSQLMigrations` again from a migrations directory and, because its base path is not the same as already processed, adds migrations to collection once more. The workaround I can offer is to slightly change  `func migrationFile() string`.  Something like this: https://gist.github.com/foxen/3dceeb90be142d71cd38e996a09d28f1

**Comment by vmihailenco** [comment]
I've tried to fix this with https://github.com/go-pg/migrations/pull/53 - please let me know if it does not help.

**Comment by vmihailenco** [comment]
`strings.Contains(f.Function, "runtime.main")` does not look right - it is only valid for your case.

**Comment by foxen** [comment]
Ok, [1e5c9da](https://github.com/go-pg/migrations/commit/1e5c9da25a2066c30cfed314d1ba338d69dd84fel) works well. Thanks.

**Comment by foxen** [comment]
It is worth mentioning one thing. If someone already have counted on recursive behavior and made structure in migrations directory, well in worse case migrations in subdirs will be ignored silently.
