### ISSUE TITLE
Breaking change in v6.7.1 for my use case.

### ISSUE THREAD

**Issue by Daavidaviid** [go-pg/migrations#60]
Hi,

I created an issue earlier -> #59 about a strange behaviour I never encountered before.
I got this after switching from GOPATH to go.mod.

What I found is that during the switching, go-pg/migration got updated to the latest version.
And after some investigation, I realized that it broke in the v6.7.1.

It seems like after the 6.7.1, the migrate tool is looking for go files at runtime, and can't find it.
While on the other hand, previous versions were working just fine.

My guess (might be wrong) is because of this commit :
[Replace filepath.Walk with ioutil.ReadDir](https://github.com/go-pg/migrations/commit/1e5c9da25a2066c30cfed314d1ba338d69dd84fe)

So I downgraded to v6.7.0 and now I'm alright.

Thanks for the work

**Comment by ernsheong** [comment]
I am also seeing this after migration to go modules:

```
panic: open /workspace/migrate: no such file or directory

goroutine 1 [running]:
github.com/go-pg/migrations.(*Collection).MustRegisterTx(...)
	/go/pkg/mod/github.com/go-pg/migrations@v6.7.2+incompatible/collection.go:333
github.com/go-pg/migrations.MustRegisterTx(0xc00004ff68, 0x2, 0x2)
	/go/pkg/mod/github.com/go-pg/migrations@v6.7.2+incompatible/default.go:35 +0x7f
main.init.0()
	/workspace/migrate/12_some_migration_description.go:33 +0x5d
panic: open /workspace/migrate: no such file or directory

goroutine 1 [running]:
github.com/go-pg/migrations.(*Collection).MustRegisterTx(...)
	/go/pkg/mod/github.com/go-pg/migrations@v6.7.2+incompatible/collection.go:333
github.com/go-pg/migrations.MustRegisterTx(0xc000051f68, 0x2, 0x2)
	/go/pkg/mod/github.com/go-pg/migrations@v6.7.2+incompatible/default.go:35 +0x7f
main.init.0()
	/workspace/migrate/12_some_migration_description.go:33 +0x5d

```

**Comment by vmihailenco** [comment]
Please try master branch.

**Comment by vmihailenco** [comment]
@Daavidaviid while it was a backwards incompatible change it is the intended and more predictable behaviour. This is how the lib going to work from now.

**Comment by ernsheong** [comment]
@vmihailenco thanks for the quick response. Migration works now. Hope it didn't kill the `DiscoverSQLMigrations` feature though, I am still using this although my latest migration is a `.go` file.
