### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by weijiangan** [go-pg/migrations#72]
I just tried the example, and it doesn't seem to read the `.go` migrations (1,2,3) and jumps straight to the `.sql` migration, which causes errors of course.

Forcing it go migrate to specific version doesn't seem to work either:
```
$ go run main.go up 1
version is 0
```

It seems that it might have something to do with the recent update.

**Comment by vmihailenco** [comment]
It works for me. Make sure to enable go modules via GO111MODULE=on.
