### ISSUE TITLE
github.com/go-pg/pg/v9 is missing

### ISSUE THREAD

**Issue by Montesk** [go-pg/migrations#76]
Can't install go-pg packages as dependency, seems to be no longer available.
I tried to make installation with "go dep" dependency manager.

I've got the multiple errors
`github.com/go-pg/pg/v9 is missing; required by github.com/go-pg/migrations@v7.1.3.`

**Comment by vmihailenco** [comment]
You need to migrate to [Go modules](https://github.com/golang/go/wiki/Modules) or stay on the old version.
