### ISSUE TITLE
Cannot have multiple "down" migrations per file

### ISSUE THREAD

**Issue by toddkazakov** [go-pg/migrations#8]
If we register multiple migrations per file, executing "up" works as expected, executing all of them, but not "down". It only executes the first migration in the list. This can be seen [here](https://github.com/go-pg/migrations/blob/v4/migrations.go#L83) and [here](https://github.com/go-pg/migrations/blob/v4/migrations.go#L108)

**Comment by vmihailenco** [comment]
Code works as expected:
- `up` applies all migrations, e.g. it runs migration 1, 2, 3, 4, 5 etc
- `down` reverts the last migration

But this lib does support multiple migrations per file. As a workaround you can use:

```
func init() {
	migrations.Register(func(db migrations.DB) error {
		if err := up1(); err != nil { return err }
		if err := up2(); err != nil { return err }
		return nil
	}, func(db migrations.DB) error {
		if err := down1(); err != nil { return err }
		if err := down2(); err != nil { return err }
		return nil
	})
}
```

**Comment by toddkazakov** [comment]
Then I guess it's just a naming problem. The workaround is good enough. Thanks.

**Comment by vmihailenco** [comment]
It is possible to add `reset` command that will revert all migrations. Not sure how useful it is.

**Comment by dhax** [comment]
Hi there,
started to use this lib and a reset command could be quite helpful during development to create a clean state database. Currently I am using this simple approach, which seems to work just fine, but maybe you have a better solution?

```
func Reset() {
	db, err := database.DBConn()
	if err != nil {
		exitf(err.Error())
	}

	version, err := migrations.Version(db)
	if err != nil {
		exitf(err.Error())
	}

	err = db.RunInTransaction(func(tx *pg.Tx) error {
		for version != 0 {
			oldVersion, newVersion, err := migrations.Run(tx, "down")
			if err != nil {
				return err
			}
			fmt.Printf("migrated from version %d to %d\n", oldVersion, newVersion)
			version = newVersion
		}
		return nil
	})
	if err != nil {
		exitf(err.Error())
	}
}
```

**Comment by vmihailenco** [comment]
Thanks for sharing. I've just added something very similar to the library
