### ISSUE TITLE
Use as a library

### ISSUE THREAD

**Issue by amonaco** [go-pg/migrations#84]
Some migration tools allow developers to use them as a standalone / CLI as well as a library. I see some changes to the Run method would be probably needed for this.

My question is:  would you guys be OK with this? Thanks

**Comment by vmihailenco** [comment]
Let's see what those changes are.

But I don't fully follow you, because go-pg/migrations does not provide any CLI / binary so you can say it is already can be used as a library. But I guess this is a matter of terminology / POV...
