### ISSUE TITLE
Use models from go-pg

### ISSUE THREAD

**Issue by Lucantas** [go-pg/migrations#86]
Is it possible to use the models from an application using go-pg? The examples only show how to work with sql files, is people actually writing those sql queries in their application or there is a way to get the dynamic query from go-pg to write migrations?

**Comment by vmihailenco** [comment]
Syre, Go-based migrations (https://github.com/go-pg/migrations/blob/master/example/2_add_id.go) can be any Go code of your choosing. You don't even have to execute SQL queries there.
